apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: agent-ops-params
    env: params.env
generatorOptions:
  disableNameSuffixHash: true
replacements:
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.agent-ops-ui-image
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].image
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.openshell-gateways
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].env.[name=OPENSHELL_GATEWAYS].value
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.openshell-discovery
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].env.[name=OPENSHELL_DISCOVERY].value
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.openshell-client-id
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].env.[name=OPENSHELL_CLIENT_ID].value
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.openshell-gateway-selector
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].env.[name=OPENSHELL_GATEWAY_SELECTOR].value
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.openshell-gateway-namespaces
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].env.[name=OPENSHELL_GATEWAY_NAMESPACES].value
  - source:
      kind: ConfigMap
      name: agent-ops-params
      fieldPath: data.gateway-domain
    targets:
      - select:
          kind: Deployment
          name: agent-ops-ui
        fieldPaths:
          - spec.template.spec.containers.[name=agent-ops-ui].env.[name=GATEWAY_DOMAIN].value
